### ISSUE TITLE
Can't join my own server

### ISSUE THREAD

**Issue by armagadon159753** [AbleUnion/able-mp#10]
### Issue description
Write a short description about the issue

### Steps to reproduce the issue

1...

2...

### OS and versions

* PHP:7.0.3
* Server OS: Android 32bit
* Game version: 1.1.5.1

### Crashdump, backtrace or other files

* ...
cb56f83

**Comment by shdudwns** [comment]
Able-mph does not support 32-bit
Only 64 bits support
Do you want to participate in development?

**Comment by shdudwns** [comment]
@armagadon159753

**Comment by djdisodo** [comment]
Sorry about that able-mp is based on bluelight(it is not supporting 32bit php)
I'ill fix that as fast as possible
But, 64bit php can use more RAM than 4GB (php 32)  
if you are using 64bit hardware please upgrade to 64bit php

Linux: https://jenkins.pmmp.io/job/PHP-7.2-Linux-x86_64/lastSuccessfulBuild/artifact/PHP_Linux-x86_64.tar.gz

Windows : https://storage.googleapis.com/itx-technologies-141911.appspot.com/php_for_genisys%2Fphp_windows_x64_7.0.17.zip

Android hardware based armv7 cpu is 32bit hardware and it based on arm64 is 64bit
But, we don't have any arm64 php binaries
