### ISSUE TITLE
플러그인 명령 오류

### ISSUE THREAD

**Issue by alvin0319** [AbleUnion/able-mp#15]
### Issue description
Write a short description about the issue

### Steps to reproduce the issue

1...

2...

### OS and versions

* PHP:7.2.0RC5
* Server OS:windows
* Game version: 1.2.7(내가 수정함)

### Crashdump, backtrace or other files

* ...
저는 앨빈입니다
근데 플러그인을 적용하면 몇몇개 플긴들 빼고는 알수없는 명령입니다 라고 뜨네요.....
특히 swarp가 로드는 정상적이게 되는데 명령어가 월드이동 말고는 안됩니다
그리고 몹들이 부자연스럽게 움직이네요.....
플러그인 끼웠을때 명령어가 사용되게 해주세요ㅠ
제발!!!!!!

**Comment by shdudwns** [comment]
와우....드디어 한국분이 쓰셨다....

**Comment by shdudwns** [comment]
블루라이트 너무 불안정하네요...그냥 pm으로 포크할 예정입니다

**Comment by alvin0319** [comment]
오 진짜요?
그럼 한번 써봐야겠네요
