### ISSUE TITLE
겉날개 작동이 이상함

### ISSUE THREAD

**Issue by djdisodo** [AbleUnion/able-mp#7]
### Issue description
Write a short description about the issue

### Steps to reproduce the issue

1...

2...

### OS and versions

* PHP:
* Server OS:
* Game version: 

### Crashdump, backtrace or other files

* ...

**Comment by shdudwns** [comment]
어케 이상함?

**Comment by djdisodo** [comment]
@shdudwns 날다가 바닥으로 쳐박힙니다 날기방지 시스템인것 같아요
