### ISSUE TITLE
이구동기 버리고 다른거로 가는거 어떨까요?

### ISSUE THREAD

**Issue by shdudwns** [AbleUnion/able-mp#8]
이유는 이구동기가 너무 불안정함.
https://github.com/ImagicalMineReactive/Leveryl
이구동기는 어떤가요?

@djdisodo @jdongel2004 
찬성할시 넘어가요

**Comment by jdongel2004** [comment]
상관 없어요. 저는 시간이 없어서 가끔 하는 사람이니..

**Comment by djdisodo** [comment]
지금까지 들인시간이 좀 아까운데...... 지금까지 개발한것도 있고...(있긴 있었나...?...)

**Comment by djdisodo** [comment]
따로 불안정하다는 느낌은 못받았는데...
